title: Hugo Icons Module
copyright: Copyright © 2022-2023 [Hugo Modules](https://hugomods.com). All Rights Reserved.
baseURL: /
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
enableRobotsTXT: true

outputs:
  home:
    - HTML
    - RSS

taxonomies:
  _merge: shallow

markup:
  _merge: deep

build:
  _merge: shallow
