main:
  - name: Icons
    identifier: icons
    weight: 10
    url: https://g0fcn.netlify.app/
    params:
      icon:
        name: icons
        vendor: fas

  - name: HB Framework
    weight: 20
    url: https://hbstack.dev/
    params:
      icon:
        name: hugo
        vendor: simple
